version: '3'
services:
  redis:
    image: 'redis:latest'
  rcli:
    image: 'redis:latest'
    links:
      - redis
    volumes:
      - redis-data:/data
    command: redis-cli -h redis
volumes:
  redis-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/data'
